{% set version = "0.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidybins
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidybins_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidybins/tidybins_{{ version }}.tar.gz
  sha256: c03cc98ac27c709317ee4472e75f724004df22dcc38300fba498e274361e4184

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-clusterr
    - r-oner
    - r-autostats
    - r-badger
    - r-dplyr
    - r-framecleaner
    - r-ggplot2
    - r-janitor
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-rlist
    - r-scales
    - r-strex
    - r-stringr
    - r-tibble
    - r-tidyselect
    - r-xgboost
  run:
    - r-base
    - r-clusterr
    - r-oner
    - r-autostats
    - r-badger
    - r-dplyr
    - r-framecleaner
    - r-ggplot2
    - r-janitor
    - r-lubridate
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-rlist
    - r-scales
    - r-strex
    - r-stringr
    - r-tibble
    - r-tidyselect
    - r-xgboost

test:
  commands:
    - $R -e "library('tidybins')"           # [not win]
    - "\"%R%\" -e \"library('tidybins')\""  # [win]

about:
  home: https://github.com/Harrison4192/tidybins
  license: GPL-3.0-or-later
  summary: Multiple ways to bin numeric columns with a tidy output. Wraps a variety of existing binning methods into one function, and includes a new method for binning by equal value, which is useful for sales data. Provides a function to automatically summarize the properties of the binned columns.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
